#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-01 19:23:19 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v411/administrating_record_company_role"

module DDEX module ERN module V411  # :nodoc: all

class DDEX::ERN::V411::AdministratingRecordCompanyWithReference < Element
  include ROXML


  xml_name "AdministratingRecordCompanyWithReference"

      xml_accessor :record_company_party_reference, :from => "RecordCompanyPartyReference", :required => true
      xml_accessor :role, :as => DDEX::ERN::V411::AdministratingRecordCompanyRole, :from => "Role", :required => true


  

end

end end end
