#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-01 19:23:19 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v411/current_territory_code"
require "ddex/ern/v411/period"
require "ddex/ern/v411/use_type"

module DDEX module ERN module V411  # :nodoc: all

class DDEX::ERN::V411::DelegatedUsageRights < Element
  include ROXML


  xml_name "DelegatedUsageRights"

      xml_accessor :use_types, :as => [DDEX::ERN::V411::UseType], :from => "UseType", :required => true
      xml_accessor :period_of_rights_delegation, :as => DDEX::ERN::V411::Period, :from => "PeriodOfRightsDelegation", :required => false
      xml_accessor :territory_of_rights_delegations, :as => [DDEX::ERN::V411::CurrentTerritoryCode], :from => "TerritoryOfRightsDelegation", :required => false


  

end

end end end
