#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-01 19:23:19 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v411/event_date_time_without_flags"
require "ddex/ern/v411/event_date_without_flags"

module DDEX module ERN module V411  # :nodoc: all

class DDEX::ERN::V411::PeriodWithoutFlags < Element
  include ROXML


  xml_name "PeriodWithoutFlags"

      xml_accessor :start_date_time, :as => DDEX::ERN::V411::EventDateTimeWithoutFlags, :from => "StartDateTime", :required => false
      xml_accessor :end_date_time, :as => DDEX::ERN::V411::EventDateTimeWithoutFlags, :from => "EndDateTime", :required => false
      xml_accessor :start_date, :as => DDEX::ERN::V411::EventDateWithoutFlags, :from => "StartDate", :required => false
      xml_accessor :end_date, :as => DDEX::ERN::V411::EventDateWithoutFlags, :from => "EndDate", :required => false


  

end

end end end
