#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/additional_title"
require "ddex/ern/v43/c_line"
require "ddex/ern/v43/contributor"
require "ddex/ern/v43/cue_origin"
require "ddex/ern/v43/cue_theme_type"
require "ddex/ern/v43/cue_use_type"
require "ddex/ern/v43/cue_visual_perception_type"
require "ddex/ern/v43/cue_vocal_type"
require "ddex/ern/v43/display_title"
require "ddex/ern/v43/display_title_text"
require "ddex/ern/v43/musical_work_id"
require "ddex/ern/v43/p_line"
require "ddex/ern/v43/resource_id"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::Cue < Element
  include ROXML


  xml_name "Cue"

      xml_accessor :cue_use_type, :as => DDEX::ERN::V43::CueUseType, :from => "CueUseType", :required => false
      xml_accessor :cue_theme_type, :as => DDEX::ERN::V43::CueThemeType, :from => "CueThemeType", :required => false
      xml_accessor :cue_vocal_type, :as => DDEX::ERN::V43::CueVocalType, :from => "CueVocalType", :required => false
      xml_accessor :cue_visual_perception_type, :as => DDEX::ERN::V43::CueVisualPerceptionType, :from => "CueVisualPerceptionType", :required => false
      xml_accessor :cue_origin, :as => DDEX::ERN::V43::CueOrigin, :from => "CueOrigin", :required => false
      xml_accessor :work_id, :as => DDEX::ERN::V43::MusicalWorkId, :from => "WorkId", :required => false
      xml_accessor :resource_id, :as => DDEX::ERN::V43::ResourceId, :from => "ResourceId", :required => false
      xml_accessor :display_title_texts, :as => [DDEX::ERN::V43::DisplayTitleText], :from => "DisplayTitleText", :required => false
      xml_accessor :display_titles, :as => [DDEX::ERN::V43::DisplayTitle], :from => "DisplayTitle", :required => false
      xml_accessor :additional_titles, :as => [DDEX::ERN::V43::AdditionalTitle], :from => "AdditionalTitle", :required => false
      xml_accessor :contributors, :as => [DDEX::ERN::V43::Contributor], :from => "Contributor", :required => false
      xml_accessor :dance?, :from => "IsDance", :required => false
      xml_accessor :has_musical_content?, :from => "HasMusicalContent", :required => false
      xml_accessor :p_lines, :as => [DDEX::ERN::V43::PLine], :from => "PLine", :required => false
      xml_accessor :c_lines, :as => [DDEX::ERN::V43::CLine], :from => "CLine", :required => false
      xml_accessor :start_time, :from => "StartTime", :required => false
      xml_accessor :duration, :from => "Duration", :required => false
      xml_accessor :end_time, :from => "EndTime", :required => false


  

end

end end end
