#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/genre_category_value"
require "ddex/ern/v43/text_without_territory"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::GenreCategory < Element
  include ROXML


  xml_name "GenreCategory"

      xml_accessor :value, :as => DDEX::ERN::V43::GenreCategoryValue, :from => "Value", :required => true
      xml_accessor :descriptions, :as => [DDEX::ERN::V43::TextWithoutTerritory], :from => "Description", :required => false


  
      xml_accessor :applicable_territory_code, :from => "@ApplicableTerritoryCode", :required => false
    
  

end

end end end
