#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::IsCredited < Element
  include ROXML


  xml_name "IsCredited"


    xml_accessor :value, :from => ".", :required => false

  
      xml_accessor :may_be_shared?, :from => "@MayBeShared", :required => false
    
  

end

end end end
