#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/party_with_role"
require "ddex/ern/v43/period"
require "ddex/ern/v43/session_type"
require "ddex/ern/v43/text_with_format"
require "ddex/ern/v43/venue"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::LocationAndDateOfSession < Element
  include ROXML


  xml_name "LocationAndDateOfSession"

      xml_accessor :session_types, :as => [DDEX::ERN::V43::SessionType], :from => "SessionType", :required => false
      xml_accessor :period, :as => DDEX::ERN::V43::Period, :from => "Period", :required => false
      xml_accessor :venues, :as => [DDEX::ERN::V43::Venue], :from => "Venue", :required => false
      xml_accessor :comment, :as => DDEX::ERN::V43::TextWithFormat, :from => "Comment", :required => false
      xml_accessor :contributors, :as => [DDEX::ERN::V43::PartyWithRole], :from => "Contributor", :required => false


  

end

end end end
