#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/message_audit_trail_event"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::MessageAuditTrail < Element
  include ROXML


  xml_name "MessageAuditTrail"

      xml_accessor :message_audit_trail_events, :as => [DDEX::ERN::V43::MessageAuditTrailEvent], :from => "MessageAuditTrailEvent", :required => true


  

end

end end end
