#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/message_header"
require "ddex/ern/v43/purged_release"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::PurgeReleaseMessage < Element
  include ROXML

    setns "ns1", "http://ddex.net/xml/ern/43"

  xml_name "PurgeReleaseMessage"

      xml_accessor :message_header, :as => DDEX::ERN::V43::MessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :purged_release, :as => DDEX::ERN::V43::PurgedRelease, :from => "PurgedRelease", :required => true


  
      xml_accessor :avs_version_id, :from => "@AvsVersionId", :required => true
    
  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => true
    
  

end

end end end
