#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/clip_release"
require "ddex/ern/v43/release"
require "ddex/ern/v43/track_release"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::ReleaseList < Element
  include ROXML


  xml_name "ReleaseList"

      xml_accessor :release, :as => DDEX::ERN::V43::Release, :from => "Release", :required => false
      xml_accessor :track_releases, :as => [DDEX::ERN::V43::TrackRelease], :from => "TrackRelease", :required => false
      xml_accessor :clip_releases, :as => [DDEX::ERN::V43::ClipRelease], :from => "ClipRelease", :required => false


  

end

end end end
