#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/audio_delivery_file"
require "ddex/ern/v43/sound_recording_clip_details"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::TechnicalSoundRecordingDetails < Element
  include ROXML


  xml_name "TechnicalSoundRecordingDetails"

      xml_accessor :technical_resource_details_reference, :from => "TechnicalResourceDetailsReference", :required => true
      xml_accessor :delivery_files, :as => [DDEX::ERN::V43::AudioDeliveryFile], :from => "DeliveryFile", :required => false
      xml_accessor :has_immersive_audio_metadata?, :from => "HasImmersiveAudioMetadata", :required => false
      xml_accessor :clip?, :from => "IsClip", :required => false
      xml_accessor :clip_details, :as => [DDEX::ERN::V43::SoundRecordingClipDetails], :from => "ClipDetails", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  
      xml_accessor :applicable_territory_code, :from => "@ApplicableTerritoryCode", :required => false
    
  
      xml_accessor :default?, :from => "@IsDefault", :required => false
    
  

end

end end end
