#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::Timing < Element
  include ROXML


  xml_name "Timing"

      xml_accessor :start_point, :as => Float, :from => "StartPoint", :required => true
      xml_accessor :end_point, :as => Float, :from => "EndPoint", :required => false
      xml_accessor :duration_useds, :as => [], :from => "DurationUsed", :required => false


  

end

end end end
