#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/all_territory_code"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::Venue < Element
  include ROXML


  xml_name "Venue"

      xml_accessor :venue_name, :from => "VenueName", :required => false
      xml_accessor :venue_address, :from => "VenueAddress", :required => false
      xml_accessor :territory_code, :as => DDEX::ERN::V43::AllTerritoryCode, :from => "TerritoryCode", :required => false
      xml_accessor :location_code, :from => "LocationCode", :required => false
      xml_accessor :venue_room, :from => "VenueRoom", :required => false


  

end

end end end
