#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v43/aspect_ratio"
require "ddex/ern/v43/audio_codec_type"
require "ddex/ern/v43/bit_rate"
require "ddex/ern/v43/container_format"
require "ddex/ern/v43/core_area"
require "ddex/ern/v43/extent"
require "ddex/ern/v43/file"
require "ddex/ern/v43/fingerprint"
require "ddex/ern/v43/frame_rate"
require "ddex/ern/v43/hdr_video_dynamic_metadata_type"
require "ddex/ern/v43/sampling_rate"
require "ddex/ern/v43/video_codec_type"
require "ddex/ern/v43/video_definition_type"

module DDEX module ERN module V43  # :nodoc: all

class DDEX::ERN::V43::VideoDeliveryFile < Element
  include ROXML


  xml_name "VideoDeliveryFile"

      xml_accessor :type, :from => "Type", :required => true
      xml_accessor :container_format, :as => DDEX::ERN::V43::ContainerFormat, :from => "ContainerFormat", :required => false
      xml_accessor :video_codec_type, :as => DDEX::ERN::V43::VideoCodecType, :from => "VideoCodecType", :required => false
      xml_accessor :video_bit_rate, :as => DDEX::ERN::V43::BitRate, :from => "VideoBitRate", :required => false
      xml_accessor :frame_rate, :as => DDEX::ERN::V43::FrameRate, :from => "FrameRate", :required => false
      xml_accessor :image_height, :as => DDEX::ERN::V43::Extent, :from => "ImageHeight", :required => false
      xml_accessor :image_width, :as => DDEX::ERN::V43::Extent, :from => "ImageWidth", :required => false
      xml_accessor :aspect_ratios, :as => [DDEX::ERN::V43::AspectRatio], :from => "AspectRatio", :required => false
      xml_accessor :core_area, :as => DDEX::ERN::V43::CoreArea, :from => "CoreArea", :required => false
      xml_accessor :color_depth, :as => Integer, :from => "ColorDepth", :required => false
      xml_accessor :video_definition_type, :as => DDEX::ERN::V43::VideoDefinitionType, :from => "VideoDefinitionType", :required => false
      xml_accessor :audio_codec_type, :as => DDEX::ERN::V43::AudioCodecType, :from => "AudioCodecType", :required => false
      xml_accessor :has_immersive_audio_metadata?, :from => "HasImmersiveAudioMetadata", :required => false
      xml_accessor :electro_optical_transfer_function_type, :from => "ElectroOpticalTransferFunctionType", :required => false
      xml_accessor :primary_color_type, :from => "PrimaryColorType", :required => false
      xml_accessor :hdr_video_dynamic_metadata_type, :as => DDEX::ERN::V43::HdrVideoDynamicMetadataType, :from => "HdrVideoDynamicMetadataType", :required => false
      xml_accessor :hdr_video_static_metadata_type, :from => "HdrVideoStaticMetadataType", :required => false
      xml_accessor :audio_bit_rate, :as => DDEX::ERN::V43::BitRate, :from => "AudioBitRate", :required => false
      xml_accessor :number_of_audio_channels, :as => Integer, :from => "NumberOfAudioChannels", :required => false
      xml_accessor :number_of_audio_objects, :as => Integer, :from => "NumberOfAudioObjects", :required => false
      xml_accessor :audio_sampling_rate, :as => DDEX::ERN::V43::SamplingRate, :from => "AudioSamplingRate", :required => false
      xml_accessor :audio_bits_per_sample, :as => Integer, :from => "AudioBitsPerSample", :required => false
      xml_accessor :duration, :from => "Duration", :required => false
      xml_accessor :bit_depth, :as => Integer, :from => "BitDepth", :required => false
      xml_accessor :file, :as => DDEX::ERN::V43::File, :from => "File", :required => false
      xml_accessor :fingerprints, :as => [DDEX::ERN::V43::Fingerprint], :from => "Fingerprint", :required => false
      xml_accessor :provided_in_delivery?, :from => "IsProvidedInDelivery", :required => false


  

end

end end end
