#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20120404/ddexc/license_or_claim_update_reason"
require "ddex/v20120404/ddexc/rights_agreement_id"

module DDEX module V20120404 module DDEXC # :nodoc: all

class RelatedLicenseOrClaimId < Element
  include ROXML


  xml_name "RelatedLicenseOrClaimId"

      xml_accessor :license_or_claim_id, :as => DDEX::V20120404::DDEXC::RightsAgreementId, :from => "LicenseOrClaimId", :required => false

      xml_accessor :license_or_claim_update_reason, :as => DDEX::V20120404::DDEXC::LicenseOrClaimUpdateReason, :from => "LicenseOrClaimUpdateReason", :required => false



  
end

end end end
