#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20120404/ddexc/sound_recording_collection_reference"

module DDEX module V20120404 module DDEXC

class SoundRecordingCollectionReferenceList < Element
  include ROXML


  xml_name "SoundRecordingCollectionReferenceList"

      xml_accessor :number_of_collections, :as => Fixnum, :from => "NumberOfCollections", :required => false

      
      xml_accessor :sound_recording_collection_references, :as => [DDEX::V20120404::DDEXC::SoundRecordingCollectionReference], :from => "SoundRecordingCollectionReference", :required => true



  
end

end end end
