#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-03-11 14:50:36 -0800
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v381/deal_reference"
require "ddex/ern/v381/deal_technical_resource_details_reference_list"
require "ddex/ern/v381/deal_terms"
require "ddex/ern/v381/resource_usage"
require "ddex/ern/v381/web_page"

module DDEX module ERN module V381  # :nodoc: all

class DDEX::ERN::V381::Deal < Element
  include ROXML


  xml_name "ns1:Deal"

      xml_accessor :deal_references, :as => [DDEX::ERN::V381::DealReference], :from => "DealReference", :required => false
      xml_accessor :deal_terms, :as => DDEX::ERN::V381::DealTerms, :from => "DealTerms", :required => false
      xml_accessor :resource_usage, :as => DDEX::ERN::V381::ResourceUsage, :from => "ResourceUsage", :required => false
      xml_accessor :deal_technical_resource_details_reference_list, :as => DDEX::ERN::V381::DealTechnicalResourceDetailsReferenceList, :from => "DealTechnicalResourceDetailsReferenceList", :required => false
      xml_accessor :distribution_channel_pages, :as => [DDEX::ERN::V381::WebPage], :from => "DistributionChannelPage", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
