#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-03-11 14:50:37 -0800
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v381/event_date"
require "ddex/ern/v381/reference_title"
require "ddex/ern/v381/release_id"
require "ddex/ern/v381/release_relationship_type"
require "ddex/ern/v381/release_summary_details_by_territory"
require "ddex/ern/v381/rights_agreement_id"

module DDEX module ERN module V381  # :nodoc: all

class DDEX::ERN::V381::RelatedRelease < Element
  include ROXML


  xml_name "ns1:RelatedRelease"

      xml_accessor :release_ids, :as => [DDEX::ERN::V381::ReleaseId], :from => "ReleaseId", :required => true
      xml_accessor :reference_title, :as => DDEX::ERN::V381::ReferenceTitle, :from => "ReferenceTitle", :required => false
      xml_accessor :release_summary_details_by_territories, :as => [DDEX::ERN::V381::ReleaseSummaryDetailsByTerritory], :from => "ReleaseSummaryDetailsByTerritory", :required => false
      xml_accessor :rights_agreement_id, :as => DDEX::ERN::V381::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :release_relationship_type, :as => DDEX::ERN::V381::ReleaseRelationshipType, :from => "ReleaseRelationshipType", :required => true
      xml_accessor :release_date, :as => DDEX::ERN::V381::EventDate, :from => "ReleaseDate", :required => false
      xml_accessor :original_release_date, :as => DDEX::ERN::V381::EventDate, :from => "OriginalReleaseDate", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
