#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-03-11 14:50:37 -0800
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v381/image"
require "ddex/ern/v381/midi"
require "ddex/ern/v381/sheet_music"
require "ddex/ern/v381/software"
require "ddex/ern/v381/sound_recording"
require "ddex/ern/v381/text"
require "ddex/ern/v381/user_defined_resource"
require "ddex/ern/v381/video"

module DDEX module ERN module V381  # :nodoc: all

class DDEX::ERN::V381::ResourceList < Element
  include ROXML


  xml_name "ns1:ResourceList"

      xml_accessor :sound_recordings, :as => [DDEX::ERN::V381::SoundRecording], :from => "SoundRecording", :required => false
      xml_accessor :midis, :as => [DDEX::ERN::V381::MIDI], :from => "MIDI", :required => false
      xml_accessor :videos, :as => [DDEX::ERN::V381::Video], :from => "Video", :required => false
      xml_accessor :images, :as => [DDEX::ERN::V381::Image], :from => "Image", :required => false
      xml_accessor :texts, :as => [DDEX::ERN::V381::Text], :from => "Text", :required => false
      xml_accessor :sheet_musics, :as => [DDEX::ERN::V381::SheetMusic], :from => "SheetMusic", :required => false
      xml_accessor :softwares, :as => [DDEX::ERN::V381::Software], :from => "Software", :required => false
      xml_accessor :user_defined_resources, :as => [DDEX::ERN::V381::UserDefinedResource], :from => "UserDefinedResource", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
