#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37/c_line"
require "ddex/ern/v37/courtesy_line"
require "ddex/ern/v37/current_territory_code"
require "ddex/ern/v37/description"
require "ddex/ern/v37/detailed_resource_contributor"
require "ddex/ern/v37/event_date"
require "ddex/ern/v37/fulfillment_date"
require "ddex/ern/v37/genre"
require "ddex/ern/v37/indirect_resource_contributor"
require "ddex/ern/v37/keywords"
require "ddex/ern/v37/name"
require "ddex/ern/v37/parental_warning_type"
require "ddex/ern/v37/synopsis"
require "ddex/ern/v37/technical_image_details"
require "ddex/ern/v37/title"

module DDEX module ERN module V37  # :nodoc: all

class ImageDetailsByTerritory < Element
  include ROXML


  xml_name "ImageDetailsByTerritory"

      
      xml_accessor :excluded_territory_codes, :as => [DDEX::ERN::V37::CurrentTerritoryCode], :from => "ExcludedTerritoryCode", :required => false

      
      xml_accessor :territory_codes, :as => [DDEX::ERN::V37::CurrentTerritoryCode], :from => "TerritoryCode", :required => false

      
      xml_accessor :titles, :as => [DDEX::ERN::V37::Title], :from => "Title", :required => false

      
      xml_accessor :resource_contributors, :as => [DDEX::ERN::V37::DetailedResourceContributor], :from => "ResourceContributor", :required => false

      
      xml_accessor :indirect_resource_contributors, :as => [DDEX::ERN::V37::IndirectResourceContributor], :from => "IndirectResourceContributor", :required => false

      
      xml_accessor :display_artist_names, :as => [DDEX::ERN::V37::Name], :from => "DisplayArtistName", :required => false

      
      xml_accessor :c_lines, :as => [DDEX::ERN::V37::CLine], :from => "CLine", :required => false

      xml_accessor :description, :as => DDEX::ERN::V37::Description, :from => "Description", :required => false

      xml_accessor :courtesy_line, :as => DDEX::ERN::V37::CourtesyLine, :from => "CourtesyLine", :required => false

      xml_accessor :resource_release_date, :as => DDEX::ERN::V37::EventDate, :from => "ResourceReleaseDate", :required => false

      xml_accessor :original_resource_release_date, :as => DDEX::ERN::V37::EventDate, :from => "OriginalResourceReleaseDate", :required => false

      xml_accessor :fulfillment_date, :as => DDEX::ERN::V37::FulfillmentDate, :from => "FulfillmentDate", :required => false

      
      xml_accessor :keywords, :as => [DDEX::ERN::V37::Keywords], :from => "Keywords", :required => false

      xml_accessor :synopsis, :as => DDEX::ERN::V37::Synopsis, :from => "Synopsis", :required => false

      
      xml_accessor :genres, :as => [DDEX::ERN::V37::Genre], :from => "Genre", :required => false

      
      xml_accessor :parental_warning_types, :as => [DDEX::ERN::V37::ParentalWarningType], :from => "ParentalWarningType", :required => false

      
      xml_accessor :technical_image_details, :as => [DDEX::ERN::V37::TechnicalImageDetails], :from => "TechnicalImageDetails", :required => false



  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
