#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37/reason"
require "ddex/ern/v37/reason_type"
require "ddex/ern/v37/release_id"

module DDEX module ERN module V37  # :nodoc: all

class SalesReportingProxyReleaseId < Element
  include ROXML


  xml_name "SalesReportingProxyReleaseId"

      xml_accessor :release_id, :as => DDEX::ERN::V37::ReleaseId, :from => "ReleaseId", :required => true
      xml_accessor :reason, :as => DDEX::ERN::V37::Reason, :from => "Reason", :required => false
      xml_accessor :reason_type, :as => DDEX::ERN::V37::ReasonType, :from => "ReasonType", :required => true


  

end

end end end
