#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V37  # :nodoc: all

class VideoCueSheetReference < Element
  include ROXML


  xml_name "VideoCueSheetReference"

      xml_accessor :video_cue_sheet_reference, :from => "VideoCueSheetReference", :required => true


  

end

end end end
