#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v312/deal_technical_resource_details_reference_list"
require "ddex/ern/v312/deal_terms"
require "ddex/ern/v312/resource_usage"
require "ddex/v20100121/ddexc/deal_reference"

module DDEX module ERN module V312  # :nodoc: all

class Deal < Element
  include ROXML


  xml_name "ns1:Deal"

      xml_accessor :deal_references, :as => [DDEX::V20100121::DDEXC::DealReference], :from => "DealReference", :required => false
      xml_accessor :deal_terms, :as => DealTerms, :from => "DealTerms", :required => false
      xml_accessor :resource_usage, :as => ResourceUsage, :from => "ResourceUsage", :required => false
      xml_accessor :deal_technical_resource_details_reference_list, :as => DealTechnicalResourceDetailsReferenceList, :from => "DealTechnicalResourceDetailsReferenceList", :required => false



      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false



end

end end end
