#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v312/deal"
require "ddex/v20100121/ddexc/release_id"

module DDEX module ERN module V312  # :nodoc: all

class ReleaseDeal < Element
  include ROXML


  xml_name "ns1:ReleaseDeal"

      xml_accessor :deal_release_references, :as => [], :from => "DealReleaseReference", :required => false
      xml_accessor :release_ids, :as => [DDEX::V20100121::DDEXC::ReleaseId], :from => "ReleaseId", :required => false
      xml_accessor :deals, :as => [Deal], :from => "Deal", :required => true
      xml_accessor :effective_date, :as => Date, :from => "EffectiveDate", :required => true



      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false



end

end end end
