#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v312/technical_sheet_music_details"
require "ddex/v20100121/ddexc/fulfillment_date"
require "ddex/v20100121/ddexc/genre"
require "ddex/v20100121/ddexc/parental_warning_type"
require "ddex/v20100121/ddexc/sheet_music_details_by_territory"

module DDEX module ERN module V312  # :nodoc: all

class SheetMusicDetailsByTerritory < DDEX::V20100121::DDEXC::SheetMusicDetailsByTerritory
  include ROXML


  xml_name "ns1:SheetMusicDetailsByTerritory"

      xml_accessor :fulfillment_date, :as => DDEX::V20100121::DDEXC::FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :genres, :as => [DDEX::V20100121::DDEXC::Genre], :from => "Genre", :required => false
      xml_accessor :parental_warning_types, :as => [DDEX::V20100121::DDEXC::ParentalWarningType], :from => "ParentalWarningType", :required => false
      xml_accessor :technical_sheet_music_details, :as => [TechnicalSheetMusicDetails], :from => "TechnicalSheetMusicDetails", :required => false




end

end end end
