#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-03-01 07:52:38 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v371/event_date"
require "ddex/ern/v371/reference_title"
require "ddex/ern/v371/release_id"
require "ddex/ern/v371/release_relationship_type"
require "ddex/ern/v371/release_summary_details_by_territory"
require "ddex/ern/v371/rights_agreement_id"

module DDEX module ERN module V371  # :nodoc: all

class RelatedRelease < Element
  include ROXML


  xml_name "RelatedRelease"

      xml_accessor :release_ids, :as => [ReleaseId], :from => "ReleaseId", :required => true
      xml_accessor :reference_title, :as => ReferenceTitle, :from => "ReferenceTitle", :required => false
      xml_accessor :release_summary_details_by_territories, :as => [ReleaseSummaryDetailsByTerritory], :from => "ReleaseSummaryDetailsByTerritory", :required => false
      xml_accessor :rights_agreement_id, :as => RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :release_relationship_type, :as => ReleaseRelationshipType, :from => "ReleaseRelationshipType", :required => true
      xml_accessor :release_date, :as => EventDate, :from => "ReleaseDate", :required => false
      xml_accessor :original_release_date, :as => EventDate, :from => "OriginalReleaseDate", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
