#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-03-01 07:52:38 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v371/party_id"
require "ddex/ern/v371/party_name"
require "ddex/ern/v371/resource_contributor_role"

module DDEX module ERN module V371  # :nodoc: all

class ResourceContributor < Element
  include ROXML


  xml_name "ns1:ResourceContributor"

      xml_accessor :party_names, :as => [PartyName], :from => "PartyName", :required => false
      xml_accessor :party_ids, :as => [PartyId], :from => "PartyId", :required => false
      xml_accessor :resource_contributor_roles, :as => [ResourceContributorRole], :from => "ResourceContributorRole", :required => false


  

      xml_accessor :sequence_number, :as => Integer, :from => "@SequenceNumber", :required => false
    
  

end

end end end
