#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-03-01 07:52:38 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v371/description"
require "ddex/ern/v371/file"
require "ddex/ern/v371/fingerprint"
require "ddex/ern/v371/fulfillment_date"
require "ddex/ern/v371/preview_details"
require "ddex/ern/v371/user_defined_value"

module DDEX module ERN module V371  # :nodoc: all

class TechnicalUserDefinedResourceDetails < Element
  include ROXML


  xml_name "TechnicalUserDefinedResourceDetails"

      xml_accessor :technical_resource_details_reference, :from => "TechnicalResourceDetailsReference", :required => true
      xml_accessor :user_defined_values, :as => [UserDefinedValue], :from => "UserDefinedValue", :required => false
      xml_accessor :preview?, :from => "IsPreview", :required => false
      xml_accessor :preview_details, :as => PreviewDetails, :from => "PreviewDetails", :required => false
      xml_accessor :fulfillment_date, :as => FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :consumer_fulfillment_date, :as => FulfillmentDate, :from => "ConsumerFulfillmentDate", :required => false
      xml_accessor :files, :as => [File], :from => "File", :required => false
      xml_accessor :file_availability_descriptions, :as => [Description], :from => "FileAvailabilityDescription", :required => false
      xml_accessor :fingerprints, :as => [Fingerprint], :from => "Fingerprint", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
