#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-03-01 07:52:38 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v371/bit_rate"

module DDEX module ERN module V371  # :nodoc: all

class TechnicalInstantiation < Element
  include ROXML


  xml_name "TechnicalInstantiation"

      xml_accessor :drm_enforcement_type, :from => "DrmEnforcementType", :required => false
      xml_accessor :video_definition_type, :from => "VideoDefinitionType", :required => false
      xml_accessor :coding_type, :from => "CodingType", :required => false
      xml_accessor :bit_rate, :as => BitRate, :from => "BitRate", :required => false


  

end

end end end
