#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-03-01 07:54:49 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37_d2/hash_sum_algorithm_type"

module DDEX module ERN module V37D2  # :nodoc: all

class HashSum < Element
  include ROXML


  xml_name "HashSum"

      xml_accessor :hash_sum, :from => "HashSum", :required => true
      xml_accessor :hash_sum_algorithm_type, :as => HashSumAlgorithmType, :from => "HashSumAlgorithmType", :required => true
      xml_accessor :hash_sum_data_type, :from => "HashSumDataType", :required => false


  

end

end end end
