#
# Auto-generated by jaxb2ruby v0.0.1 on 2018-03-01 07:54:49 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37_d2/container_format"
require "ddex/ern/v37_d2/description"
require "ddex/ern/v37_d2/drm_platform_type"
require "ddex/ern/v37_d2/file"
require "ddex/ern/v37_d2/fingerprint"
require "ddex/ern/v37_d2/fulfillment_date"
require "ddex/ern/v37_d2/preview_details"
require "ddex/ern/v37_d2/sheet_music_codec_type"

module DDEX module ERN module V37D2  # :nodoc: all

class TechnicalSheetMusicDetails < Element
  include ROXML


  xml_name "ns1:TechnicalSheetMusicDetails"

      xml_accessor :technical_resource_details_reference, :from => "TechnicalResourceDetailsReference", :required => true
      xml_accessor :drm_platform_type, :as => DrmPlatformType, :from => "DrmPlatformType", :required => false
      xml_accessor :container_format, :as => ContainerFormat, :from => "ContainerFormat", :required => false
      xml_accessor :sheet_music_codec_type, :as => SheetMusicCodecType, :from => "SheetMusicCodecType", :required => false
      xml_accessor :preview?, :from => "IsPreview", :required => false
      xml_accessor :preview_details, :as => PreviewDetails, :from => "PreviewDetails", :required => false
      xml_accessor :fulfillment_date, :as => FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :consumer_fulfillment_date, :as => FulfillmentDate, :from => "ConsumerFulfillmentDate", :required => false
      xml_accessor :files, :as => [File], :from => "File", :required => false
      xml_accessor :file_availability_descriptions, :as => [Description], :from => "FileAvailabilityDescription", :required => false
      xml_accessor :fingerprints, :as => [Fingerprint], :from => "Fingerprint", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
