#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v2011/amep/v11/ws_message_header"
require "ddex/v20110120/ddexc/party_descriptor"
require "ddex/v20110120/ddexc/period"

module DDEX module ECHO module V11  # :nodoc: all

class InformationAboutAvailableReleaseRequestMessage < Element
  include ROXML

    setns "echo", "http://ddex.net/xml/2011/echo/11"

  xml_name "InformationAboutAvailableReleaseRequestMessage"

      xml_accessor :message_header, :as => DDEX::V2011::AMEP::V11::WsMessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :dsp, :as => DDEX::V20110120::DDEXC::PartyDescriptor, :from => "DSP", :required => true
      xml_accessor :period, :as => DDEX::V20110120::DDEXC::Period, :from => "Period", :required => false


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  

end

end end end
