#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/echo/v11/ws_acknowledgement"
require "ddex/v20110120/ddexc/event_date"

module DDEX module ECHO module V11  # :nodoc: all

class InformationAboutAvailableReleaseResponseMessage < DDEX::ECHO::V11::WsAcknowledgement
  include ROXML

    setns "echo", "http://ddex.net/xml/2011/echo/11"

  xml_name "InformationAboutAvailableReleaseResponseMessage"

      xml_accessor :ticket_id, :from => "TicketId", :required => true
      xml_accessor :estimated_date_time_of_delivery, :as => DDEX::V20110120::DDEXC::EventDate, :from => "EstimatedDateTimeOfDelivery", :required => true


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  

end

end end end
