#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/echo/v11/message_in_batch"
require "ddex/v2011/amep/v11/ftp_message_header"
require "ddex/v20110120/ddexc/message_action_type"
require "ddex/v20110120/ddexc/product_type"

module DDEX module ECHO module V11  # :nodoc: all

class ManifestMessage < Element
  include ROXML

    setns "echo", "http://ddex.net/xml/2011/echo/11"

  xml_name "ManifestMessage"

      xml_accessor :message_header, :as => DDEX::V2011::AMEP::V11::FtpMessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :test_flag?, :from => "IsTestFlag", :required => false
      xml_accessor :delivery_type, :as => DDEX::V20110120::DDEXC::MessageActionType, :from => "DeliveryType", :required => true
      xml_accessor :batch_product_type, :as => DDEX::V20110120::DDEXC::ProductType, :from => "BatchProductType", :required => true
      xml_accessor :root_directory, :from => "RootDirectory", :required => true
      xml_accessor :number_of_messages, :as => Integer, :from => "NumberOfMessages", :required => true
      xml_accessor :message_in_batches, :as => [DDEX::ECHO::V11::MessageInBatch], :from => "MessageInBatch", :required => true


  
      xml_accessor :message_version_id, :from => "@MessageVersionId", :required => true
    
  
  alias :_message_version_id :message_version_id
  private :_message_version_id

  def message_version_id
    _message_version_id || DDEX::ECHO.config["V11"][:message_version_id]
  end

end

end end end
