#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ECHO module V11  # :nodoc: all

class MaximumDeliveriesPerDay < Element
  include ROXML


  xml_name "MaximumDeliveriesPerDay"

      xml_accessor :number_of_messages, :as => Integer, :from => "NumberOfMessages", :required => false
      xml_accessor :number_of_bytes, :as => Integer, :from => "NumberOfBytes", :required => false


  

end

end end end
