#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/echo/v11/release_in_queue"

module DDEX module ECHO module V11  # :nodoc: all

class ReleaseInQueueList < Element
  include ROXML


  xml_name "ReleaseInQueueList"

      xml_accessor :release_in_queues, :as => [DDEX::ECHO::V11::ReleaseInQueue], :from => "ReleaseInQueue", :required => true


  

end

end end end
