#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-14 23:25:45 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v382/collection_work_reference"

module DDEX module ERN module V382  # :nodoc: all

class DDEX::ERN::V382::CollectionWorkReferenceList < Element
  include ROXML


  xml_name "CollectionWorkReferenceList"

      xml_accessor :collection_work_references, :as => [DDEX::ERN::V382::CollectionWorkReference], :from => "CollectionWorkReference", :required => true




end

end end end
