#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-14 23:25:45 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v382/cue"
require "ddex/ern/v382/cue_sheet_type"
require "ddex/ern/v382/proprietary_id"

module DDEX module ERN module V382  # :nodoc: all

class DDEX::ERN::V382::CueSheet < Element
  include ROXML


  xml_name "CueSheet"

      xml_accessor :cue_sheet_ids, :as => [DDEX::ERN::V382::ProprietaryId], :from => "CueSheetId", :required => false
      xml_accessor :cue_sheet_reference, :from => "CueSheetReference", :required => true
      xml_accessor :cue_sheet_type, :as => DDEX::ERN::V382::CueSheetType, :from => "CueSheetType", :required => true
      xml_accessor :cues, :as => [DDEX::ERN::V382::Cue], :from => "Cue", :required => true




end

end end end
