#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-14 23:25:46 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v382/musical_work_contributor"
require "ddex/ern/v382/musical_work_details_by_territory"
require "ddex/ern/v382/musical_work_id"
require "ddex/ern/v382/musical_work_type"
require "ddex/ern/v382/reference_title"
require "ddex/ern/v382/right_share"
require "ddex/ern/v382/rights_agreement_id"

module DDEX module ERN module V382  # :nodoc: all

class DDEX::ERN::V382::MusicalWork < Element
  include ROXML


  xml_name "MusicalWork"

      xml_accessor :musical_work_ids, :as => [DDEX::ERN::V382::MusicalWorkId], :from => "MusicalWorkId", :required => true
      xml_accessor :musical_work_reference, :from => "MusicalWorkReference", :required => true
      xml_accessor :reference_titles, :as => [DDEX::ERN::V382::ReferenceTitle], :from => "ReferenceTitle", :required => true
      xml_accessor :rights_agreement_id, :as => DDEX::ERN::V382::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :musical_work_contributors, :as => [DDEX::ERN::V382::MusicalWorkContributor], :from => "MusicalWorkContributor", :required => true
      xml_accessor :musical_work_types, :as => [DDEX::ERN::V382::MusicalWorkType], :from => "MusicalWorkType", :required => false
      xml_accessor :right_shares, :as => [DDEX::ERN::V382::RightShare], :from => "RightShare", :required => false
      xml_accessor :musical_work_details_by_territories, :as => [DDEX::ERN::V382::MusicalWorkDetailsByTerritory], :from => "MusicalWorkDetailsByTerritory", :required => false



      xml_accessor :updated?, :from => "@IsUpdated", :required => false


      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false



end

end end end
