#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-14 23:25:47 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v382/release_resource_reference"

module DDEX module ERN module V382  # :nodoc: all

class DDEX::ERN::V382::ReleaseResourceReferenceList < Element
  include ROXML


  xml_name "ReleaseResourceReferenceList"

      xml_accessor :release_resource_references, :as => [DDEX::ERN::V382::ReleaseResourceReference], :from => "ReleaseResourceReference", :required => true




end

end end end
