#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-14 23:25:47 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v382/artist"
require "ddex/ern/v382/av_rating"
require "ddex/ern/v382/comment"
require "ddex/ern/v382/courtesy_line"
require "ddex/ern/v382/current_territory_code"
require "ddex/ern/v382/detailed_resource_contributor"
require "ddex/ern/v382/event_date"
require "ddex/ern/v382/fulfillment_date"
require "ddex/ern/v382/genre"
require "ddex/ern/v382/host_sound_carrier"
require "ddex/ern/v382/indirect_resource_contributor"
require "ddex/ern/v382/keywords"
require "ddex/ern/v382/label_name"
require "ddex/ern/v382/name"
require "ddex/ern/v382/p_line"
require "ddex/ern/v382/parental_warning_type"
require "ddex/ern/v382/rights_agreement_id"
require "ddex/ern/v382/synopsis"
require "ddex/ern/v382/technical_sound_recording_details"
require "ddex/ern/v382/title"
require "ddex/ern/v382/typed_rights_controller"

module DDEX module ERN module V382  # :nodoc: all

class DDEX::ERN::V382::SoundRecordingDetailsByTerritory < Element
  include ROXML


  xml_name "SoundRecordingDetailsByTerritory"

      xml_accessor :excluded_territory_codes, :as => [DDEX::ERN::V382::CurrentTerritoryCode], :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :as => [DDEX::ERN::V382::CurrentTerritoryCode], :from => "TerritoryCode", :required => false
      xml_accessor :titles, :as => [DDEX::ERN::V382::Title], :from => "Title", :required => false
      xml_accessor :display_artists, :as => [DDEX::ERN::V382::Artist], :from => "DisplayArtist", :required => false
      xml_accessor :display_conductors, :as => [DDEX::ERN::V382::Artist], :from => "DisplayConductor", :required => false
      xml_accessor :resource_contributors, :as => [DDEX::ERN::V382::DetailedResourceContributor], :from => "ResourceContributor", :required => false
      xml_accessor :indirect_resource_contributors, :as => [DDEX::ERN::V382::IndirectResourceContributor], :from => "IndirectResourceContributor", :required => false
      xml_accessor :rights_agreement_id, :as => DDEX::ERN::V382::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :display_artist_names, :as => [DDEX::ERN::V382::Name], :from => "DisplayArtistName", :required => false
      xml_accessor :label_names, :as => [DDEX::ERN::V382::LabelName], :from => "LabelName", :required => false
      xml_accessor :rights_controllers, :as => [DDEX::ERN::V382::TypedRightsController], :from => "RightsController", :required => false
      xml_accessor :remastered_date, :as => DDEX::ERN::V382::EventDate, :from => "RemasteredDate", :required => false
      xml_accessor :resource_release_date, :as => DDEX::ERN::V382::EventDate, :from => "ResourceReleaseDate", :required => false
      xml_accessor :original_resource_release_date, :as => DDEX::ERN::V382::EventDate, :from => "OriginalResourceReleaseDate", :required => false
      xml_accessor :p_lines, :as => [DDEX::ERN::V382::PLine], :from => "PLine", :required => false
      xml_accessor :courtesy_line, :as => DDEX::ERN::V382::CourtesyLine, :from => "CourtesyLine", :required => false
      xml_accessor :sequence_number, :as => Integer, :from => "SequenceNumber", :required => false
      xml_accessor :host_sound_carriers, :as => [DDEX::ERN::V382::HostSoundCarrier], :from => "HostSoundCarrier", :required => false
      xml_accessor :marketing_comment, :as => DDEX::ERN::V382::Comment, :from => "MarketingComment", :required => false
      xml_accessor :genres, :as => [DDEX::ERN::V382::Genre], :from => "Genre", :required => false
      xml_accessor :parental_warning_types, :as => [DDEX::ERN::V382::ParentalWarningType], :from => "ParentalWarningType", :required => false
      xml_accessor :av_ratings, :as => [DDEX::ERN::V382::AvRating], :from => "AvRating", :required => false
      xml_accessor :technical_sound_recording_details, :as => [DDEX::ERN::V382::TechnicalSoundRecordingDetails], :from => "TechnicalSoundRecordingDetails", :required => false
      xml_accessor :fulfillment_date, :as => DDEX::ERN::V382::FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :keywords, :as => [DDEX::ERN::V382::Keywords], :from => "Keywords", :required => false
      xml_accessor :synopsis, :as => DDEX::ERN::V382::Synopsis, :from => "Synopsis", :required => false



      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false



end

end end end
