#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-14 23:25:47 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v382/carrier_type"
require "ddex/ern/v382/distribution_channel_type"
require "ddex/ern/v382/technical_instantiation"
require "ddex/ern/v382/use_type"
require "ddex/ern/v382/user_interface_type"

module DDEX module ERN module V382  # :nodoc: all

class DDEX::ERN::V382::Usage < Element
  include ROXML


  xml_name "Usage"

      xml_accessor :use_types, :as => [DDEX::ERN::V382::UseType], :from => "UseType", :required => true
      xml_accessor :user_interface_types, :as => [DDEX::ERN::V382::UserInterfaceType], :from => "UserInterfaceType", :required => false
      xml_accessor :distribution_channel_types, :as => [DDEX::ERN::V382::DistributionChannelType], :from => "DistributionChannelType", :required => false
      xml_accessor :carrier_types, :as => [DDEX::ERN::V382::CarrierType], :from => "CarrierType", :required => false
      xml_accessor :technical_instantiation, :as => DDEX::ERN::V382::TechnicalInstantiation, :from => "TechnicalInstantiation", :required => false
      xml_accessor :number_of_usages, :as => Integer, :from => "NumberOfUsages", :required => false




end

end end end
