#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "w3/v2000/v09/xmldsig/reference"

module W3 module V2000 module V09 module XMLDsig  # :nodoc: all

class Manifest < DDEX::Element
  include ROXML

    setns "xmldsig", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "Manifest"

      xml_accessor :references, :as => [W3::V2000::V09::XMLDsig::Reference], :from => "ns6:Reference", :required => true


  
      xml_accessor :id, :from => "@Id", :required => false
    
  

end

end end end end
