#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

module W3 module V2000 module V09 module XMLDsig  # :nodoc: all

class PGPData < DDEX::Element
  include ROXML

    setns "xmldsig", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "PGPData"

      xml_accessor :pgp_key_id, :from => "ns6:PGPKeyID", :required => false
      xml_accessor :pgp_key_packet, :from => "ns6:PGPKeyPacket", :required => false
      xml_accessor :anies, :as => [DDEX::Element], :from => "anies", :required => false


  

end

end end end end
