#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module W3 module V2000 module V09 module XMLDsig  # :nodoc: all

class RSAKeyValue < DDEX::Element
  include ROXML

    setns "xmldsig", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "RSAKeyValue"

      xml_accessor :modulus, :from => "ns6:Modulus", :required => true
      xml_accessor :exponent, :from => "ns6:Exponent", :required => true


  

end

end end end end
