#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module W3 module V2000 module V09 module XMLDsig  # :nodoc: all

class X509Data < DDEX::Element
  include ROXML

    setns "xmldsig", "http://www.w3.org/2000/09/xmldsig#"

  xml_name "X509Data"

      xml_accessor :x509_issuer_serials_and_x509_skis_and_x509_subject_names, :as => [], :from => "x509IssuerSerialsAndX509SKISAndX509SubjectNames", :required => false


  

end

end end end end
