#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-09 22:38:54 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20100712/ddexc/character"
require "ddex/v20100712/ddexc/collection_details_by_territory"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::CollectionDetailsByTerritory < DDEX::V20100712::DDEXC::CollectionDetailsByTerritory
  include ROXML


  xml_name "CollectionDetailsByTerritory"

      xml_accessor :characters, :as => [DDEX::V20100712::DDEXC::Character], :from => "Character", :required => false




end

end end end
