#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-09 22:38:54 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v32/cue_sheet"

module DDEX module ERN module V32  # :nodoc: all

class DDEX::ERN::V32::CueSheetList < Element
  include ROXML


  xml_name "ns1:CueSheetList"

      xml_accessor :cue_sheets, :as => [DDEX::ERN::V32::CueSheet], :from => "CueSheet", :required => true


  

end

end end end
