#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20121219/ddexc/name"
require "ddex/v20121219/ddexc/party_id"
require "ddex/v20121219/ddexc/release_id"

module DDEX module V20121219 module DDEXC # :nodoc: all

class WebPage < Element
  include ROXML


  xml_name "WebPage"

      
      xml_accessor :party_ids, :as => [DDEX::V20121219::DDEXC::PartyId], :from => "PartyId", :required => false

      
      xml_accessor :release_ids, :as => [DDEX::V20121219::DDEXC::ReleaseId], :from => "ReleaseId", :required => false

      xml_accessor :page_name, :as => DDEX::V20121219::DDEXC::Name, :from => "PageName", :required => false

      xml_accessor :url, :from => "URL", :required => false

      xml_accessor :user_name, :from => "UserName", :required => false

      xml_accessor :password, :from => "Password", :required => false



  
end

end end end
