#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20110630/ddexc/party_descriptor"

module DDEX module V20110630 module DDEXC # :nodoc: all

class AdministratingRecordCompany < DDEX::V20110630::DDEXC::PartyDescriptor
  include ROXML


  xml_name "AdministratingRecordCompany"



  
      xml_accessor :role, :from => "@Role", :required => true
    
  
end

end end end
