#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20110630/ddexc/title_text"
require "ddex/v20110630/ddexc/typed_sub_title"

module DDEX module V20110630 module DDEXC  # :nodoc: all

class Title < Element
  include ROXML


  xml_name "Title"

      xml_accessor :title_text, :as => DDEX::V20110630::DDEXC::TitleText, :from => "TitleText", :required => true
      xml_accessor :sub_titles, :as => [DDEX::V20110630::DDEXC::TypedSubTitle], :from => "SubTitle", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  
      xml_accessor :title_type, :from => "@TitleType", :required => false
    
  

end

end end end
