#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20120719/ddexc/party_id"
require "ddex/v20120719/ddexc/party_name"

module DDEX module V20120719 module DDEXC

class AdministratingRecordCompany < Element
  include ROXML


  xml_name "AdministratingRecordCompany"

      
      xml_accessor :party_names, :as => [DDEX::V20120719::DDEXC::PartyName], :from => "PartyName", :required => false

      xml_accessor :party_id, :as => DDEX::V20120719::DDEXC::PartyId, :from => "PartyId", :required => false



  
      xml_accessor :namespace, :from => "@Namespace", :required => false
    
  
      xml_accessor :user_defined_value, :from => "@UserDefinedValue", :required => false
    
  
      xml_accessor :role, :from => "@Role", :required => true
    
  
end

end end end
