#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20120719/ddexc/message_audit_trail_event"

module DDEX module V20120719 module DDEXC

class MessageAuditTrail < Element
  include ROXML


  xml_name "MessageAuditTrail"

      
      xml_accessor :message_audit_trail_events, :as => [DDEX::V20120719::DDEXC::MessageAuditTrailEvent], :from => "MessageAuditTrailEvent", :required => true



  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  
end

end end end
