#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-03 10:00:54 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v42/rating_agency"
require "ddex/ern/v42/rating_reason"

module DDEX module ERN module V42  # :nodoc: all

class DDEX::ERN::V42::AvRating < Element
  include ROXML


  xml_name "AvRating"

      xml_accessor :rating, :from => "Rating", :required => true
      xml_accessor :agency, :as => DDEX::ERN::V42::RatingAgency, :from => "Agency", :required => true
      xml_accessor :reason, :as => DDEX::ERN::V42::RatingReason, :from => "Reason", :required => false


  
      xml_accessor :applicable_territory_code, :from => "@ApplicableTerritoryCode", :required => false
    
  
      xml_accessor :default?, :from => "@IsDefault", :required => false
    
  

end

end end end
