#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-03 10:00:54 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v42/contributor"

module DDEX module ERN module V42  # :nodoc: all

class DDEX::ERN::V42::Character < Element
  include ROXML


  xml_name "Character"

      xml_accessor :character_party_reference, :from => "CharacterPartyReference", :required => true
      xml_accessor :performer, :as => DDEX::ERN::V42::Contributor, :from => "Performer", :required => false


  

      xml_accessor :sequence_number, :as => Integer, :from => "@SequenceNumber", :required => false
    
  

end

end end end
