#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-03 10:00:54 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V42  # :nodoc: all

class DDEX::ERN::V42::CoreArea < Element
  include ROXML


  xml_name "CoreArea"

      xml_accessor :top_left_corner, :from => "TopLeftCorner", :required => true
      xml_accessor :bottom_right_corner, :from => "BottomRightCorner", :required => true


  

end

end end end
