#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-03 10:00:54 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v42/deal_technical_resource_details_reference_list"
require "ddex/ern/v42/deal_terms"
require "ddex/ern/v42/distribution_channel_page"

module DDEX module ERN module V42  # :nodoc: all

class DDEX::ERN::V42::Deal < Element
  include ROXML


  xml_name "Deal"

      xml_accessor :deal_references, :as => [], :from => "DealReference", :required => false
      xml_accessor :communicated_out_of_band?, :from => "IsCommunicatedOutOfBand", :required => false
      xml_accessor :deal_terms, :as => DDEX::ERN::V42::DealTerms, :from => "DealTerms", :required => false
      xml_accessor :deal_technical_resource_details_reference_list, :as => DDEX::ERN::V42::DealTechnicalResourceDetailsReferenceList, :from => "DealTechnicalResourceDetailsReferenceList", :required => false
      xml_accessor :distribution_channel_pages, :as => [DDEX::ERN::V42::DistributionChannelPage], :from => "DistributionChannelPage", :required => false


  

end

end end end
