#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-03 10:00:55 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v42/resource_id"
require "ddex/ern/v42/timing"

module DDEX module ERN module V42  # :nodoc: all

class DDEX::ERN::V42::RelatedResource < Element
  include ROXML


  xml_name "RelatedResource"

      xml_accessor :resource_relationship_type, :from => "ResourceRelationshipType", :required => true
      xml_accessor :resource_id, :as => DDEX::ERN::V42::ResourceId, :from => "ResourceId", :required => false
      xml_accessor :resource_related_resource_reference, :from => "ResourceRelatedResourceReference", :required => false
      xml_accessor :timings, :as => [DDEX::ERN::V42::Timing], :from => "Timing", :required => false


  

end

end end end
