#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-12-03 10:00:56 -0500
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v42/file"

module DDEX module ERN module V42  # :nodoc: all

class DDEX::ERN::V42::SupplementalDocumentList < Element
  include ROXML


  xml_name "SupplementalDocumentList"

      xml_accessor :supplemental_documents, :as => [DDEX::ERN::V42::File], :from => "SupplementalDocument", :required => true


  

end

end end end
