#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-07-27 20:26:15 -0400
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/release_deal"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::DealList < Element
  include ROXML


  xml_name "DealList"

      xml_accessor :release_deals, :as => [DDEX::ERN::V41::ReleaseDeal], :from => "ReleaseDeal", :required => true


  

end

end end end
