#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-07-27 20:26:16 -0400
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/cue_sheet_type"
require "ddex/ern/v41/detailed_cue"
require "ddex/ern/v41/proprietary_id"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::DetailedCueSheet < Element
  include ROXML


  xml_name "DetailedCueSheet"

      xml_accessor :cue_sheet_ids, :as => [DDEX::ERN::V41::ProprietaryId], :from => "CueSheetId", :required => false
      xml_accessor :cue_sheet_reference, :from => "CueSheetReference", :required => true
      xml_accessor :cue_sheet_type, :as => DDEX::ERN::V41::CueSheetType, :from => "CueSheetType", :required => true
      xml_accessor :cues, :as => [DDEX::ERN::V41::DetailedCue], :from => "Cue", :required => true


  

end

end end end
