#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-07-27 20:26:16 -0400
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/chapter_list"
require "ddex/ern/v41/deal_list"
require "ddex/ern/v41/detailed_cue_sheet_list"
require "ddex/ern/v41/message_header"
require "ddex/ern/v41/party_list"
require "ddex/ern/v41/release_list"
require "ddex/ern/v41/resource_list"
require "ddex/ern/v41/supplemental_document_list"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::NewReleaseMessage < Element
  include ROXML

    setns "ns1", "http://ddex.net/xml/ern/41"

  xml_name "NewReleaseMessage"

      xml_accessor :message_header, :as => DDEX::ERN::V41::MessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :party_list, :as => DDEX::ERN::V41::PartyList, :from => "PartyList", :required => true
      xml_accessor :cue_sheet_list, :as => DDEX::ERN::V41::DetailedCueSheetList, :from => "CueSheetList", :required => false
      xml_accessor :resource_list, :as => DDEX::ERN::V41::ResourceList, :from => "ResourceList", :required => true
      xml_accessor :chapter_list, :as => DDEX::ERN::V41::ChapterList, :from => "ChapterList", :required => false
      xml_accessor :release_list, :as => DDEX::ERN::V41::ReleaseList, :from => "ReleaseList", :required => true
      xml_accessor :deal_list, :as => DDEX::ERN::V41::DealList, :from => "DealList", :required => false
      xml_accessor :supplemental_document_list, :as => DDEX::ERN::V41::SupplementalDocumentList, :from => "SupplementalDocumentList", :required => false


  
      xml_accessor :release_profile_version_id, :from => "@ReleaseProfileVersionId", :required => false
    
  
      xml_accessor :release_profile_variant_version_id, :from => "@ReleaseProfileVariantVersionId", :required => false
    
  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => true
    
  

end

end end end
