#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-07-27 20:26:16 -0400
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/image"
require "ddex/ern/v41/sheet_music"
require "ddex/ern/v41/software"
require "ddex/ern/v41/sound_recording"
require "ddex/ern/v41/text"
require "ddex/ern/v41/video"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::ResourceList < Element
  include ROXML


  xml_name "ResourceList"

      xml_accessor :sound_recordings, :as => [DDEX::ERN::V41::SoundRecording], :from => "SoundRecording", :required => false
      xml_accessor :videos, :as => [DDEX::ERN::V41::Video], :from => "Video", :required => false
      xml_accessor :images, :as => [DDEX::ERN::V41::Image], :from => "Image", :required => false
      xml_accessor :texts, :as => [DDEX::ERN::V41::Text], :from => "Text", :required => false
      xml_accessor :sheet_musics, :as => [DDEX::ERN::V41::SheetMusic], :from => "SheetMusic", :required => false
      xml_accessor :softwares, :as => [DDEX::ERN::V41::Software], :from => "Software", :required => false


  

end

end end end
