#
# Auto-generated by jaxb2ruby v0.0.1 on 2020-07-27 20:26:16 -0400
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/aspect_ratio"
require "ddex/ern/v41/audio_codec_type"
require "ddex/ern/v41/bit_rate"
require "ddex/ern/v41/container_format"
require "ddex/ern/v41/core_area"
require "ddex/ern/v41/extent"
require "ddex/ern/v41/file"
require "ddex/ern/v41/fingerprint"
require "ddex/ern/v41/frame_rate"
require "ddex/ern/v41/sampling_rate"
require "ddex/ern/v41/sound_recording_preview_details"
require "ddex/ern/v41/video_codec_type"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::TechnicalVideoDetails < Element
  include ROXML


  xml_name "TechnicalVideoDetails"

      xml_accessor :technical_resource_details_reference, :from => "TechnicalResourceDetailsReference", :required => true
      xml_accessor :overall_bit_rate, :as => DDEX::ERN::V41::BitRate, :from => "OverallBitRate", :required => false
      xml_accessor :container_format, :as => DDEX::ERN::V41::ContainerFormat, :from => "ContainerFormat", :required => false
      xml_accessor :video_codec_type, :as => DDEX::ERN::V41::VideoCodecType, :from => "VideoCodecType", :required => false
      xml_accessor :video_bit_rate, :as => DDEX::ERN::V41::BitRate, :from => "VideoBitRate", :required => false
      xml_accessor :frame_rate, :as => DDEX::ERN::V41::FrameRate, :from => "FrameRate", :required => false
      xml_accessor :image_height, :as => DDEX::ERN::V41::Extent, :from => "ImageHeight", :required => false
      xml_accessor :image_width, :as => DDEX::ERN::V41::Extent, :from => "ImageWidth", :required => false
      xml_accessor :aspect_ratio, :as => DDEX::ERN::V41::AspectRatio, :from => "AspectRatio", :required => false
      xml_accessor :core_area, :as => DDEX::ERN::V41::CoreArea, :from => "CoreArea", :required => false
      xml_accessor :color_depth, :as => Integer, :from => "ColorDepth", :required => false
      xml_accessor :video_definition_type, :from => "VideoDefinitionType", :required => false
      xml_accessor :audio_codec_type, :as => DDEX::ERN::V41::AudioCodecType, :from => "AudioCodecType", :required => false
      xml_accessor :audio_bit_rate, :as => DDEX::ERN::V41::BitRate, :from => "AudioBitRate", :required => false
      xml_accessor :number_of_audio_channels, :as => Integer, :from => "NumberOfAudioChannels", :required => false
      xml_accessor :audio_sampling_rate, :as => DDEX::ERN::V41::SamplingRate, :from => "AudioSamplingRate", :required => false
      xml_accessor :audio_bits_per_sample, :as => Integer, :from => "AudioBitsPerSample", :required => false
      xml_accessor :duration, :from => "Duration", :required => false
      xml_accessor :bit_depth, :as => Integer, :from => "BitDepth", :required => false
      xml_accessor :preview?, :from => "IsPreview", :required => false
      xml_accessor :preview_details, :as => DDEX::ERN::V41::SoundRecordingPreviewDetails, :from => "PreviewDetails", :required => false
      xml_accessor :file, :as => DDEX::ERN::V41::File, :from => "File", :required => false
      xml_accessor :fingerprints, :as => [DDEX::ERN::V41::Fingerprint], :from => "Fingerprint", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  
      xml_accessor :applicable_territory_code, :from => "@ApplicableTerritoryCode", :required => false
    
  
      xml_accessor :default?, :from => "@IsDefault", :required => false
    
  

end

end end end
