#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V33  # :nodoc: all

class DealTechnicalResourceDetailsReferenceList < Element
  include ROXML


  xml_name "DealTechnicalResourceDetailsReferenceList"

      xml_accessor :deal_technical_resource_details_references, :as => [], :from => "DealTechnicalResourceDetailsReference", :required => false


  

end

end end end
