#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-03-12 19:07:04 -0800
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v38/cue_sheet"

module DDEX module ERN module V38  # :nodoc: all

class DDEX::ERN::V38::CueSheetList < Element
  include ROXML


  xml_name "CueSheetList"

      xml_accessor :cue_sheets, :as => [DDEX::ERN::V38::CueSheet], :from => "CueSheet", :required => true


  

end

end end end
