#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20100121/ddexc/resource_contributor"
require "ddex/v20100121/ddexc/title"

module DDEX module V20100121 module DDEXC  # :nodoc: all

class CollectionDetailsByTerritory < Element
  include ROXML


  xml_name "ns2:CollectionDetailsByTerritory"

      xml_accessor :excluded_territory_codes, :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :from => "TerritoryCode", :required => false
      xml_accessor :titles, :as => [DDEX::V20100121::DDEXC::Title], :from => "Title", :required => false
      xml_accessor :contributors, :as => [DDEX::V20100121::DDEXC::ResourceContributor], :from => "Contributor", :required => false




end

end end end
