#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20100121/ddexc/name"
require "ddex/v20100121/ddexc/rights_agreement_id"

module DDEX module V20100121 module DDEXC  # :nodoc: all

class ReleaseSummaryDetailsByTerritory < Element
  include ROXML


  xml_name "ns2:ReleaseSummaryDetailsByTerritory"

      xml_accessor :excluded_territory_codes, :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :from => "TerritoryCode", :required => false
      xml_accessor :display_artist_name, :as => DDEX::V20100121::DDEXC::Name, :from => "DisplayArtistName", :required => false
      xml_accessor :label_name, :as => DDEX::V20100121::DDEXC::Name, :from => "LabelName", :required => false
      xml_accessor :rights_agreement_id, :as => DDEX::V20100121::DDEXC::RightsAgreementId, :from => "RightsAgreementId", :required => false



      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false



end

end end end
