#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20100121/ddexc/administrating_record_company"
require "ddex/v20100121/ddexc/display_artist"
require "ddex/v20100121/ddexc/related_release"
require "ddex/v20100121/ddexc/release_summary_details_by_territory"
require "ddex/v20100121/ddexc/release_type"
require "ddex/v20100121/ddexc/title"

module DDEX module V20100121 module DDEXC  # :nodoc: all

class ReleaseDetailsByTerritory < DDEX::V20100121::DDEXC::ReleaseSummaryDetailsByTerritory
  include ROXML


  xml_name "ns2:ReleaseDetailsByTerritory"

      xml_accessor :titles, :as => [DDEX::V20100121::DDEXC::Title], :from => "Title", :required => false
      xml_accessor :display_artists, :as => [DDEX::V20100121::DDEXC::DisplayArtist], :from => "DisplayArtist", :required => true
      xml_accessor :multi_artist_compilation?, :from => "IsMultiArtistCompilation", :required => false
      xml_accessor :administrating_record_companies, :as => [DDEX::V20100121::DDEXC::AdministratingRecordCompany], :from => "AdministratingRecordCompany", :required => false
      xml_accessor :release_types, :as => [DDEX::V20100121::DDEXC::ReleaseType], :from => "ReleaseType", :required => false
      xml_accessor :related_releases, :as => [DDEX::V20100121::DDEXC::RelatedRelease], :from => "RelatedRelease", :required => false




end

end end end
