#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module V20100121 module DDEXC  # :nodoc: all

class ResourceMusicalWorkReference < Element
  include ROXML


  xml_name "ns2:ResourceMusicalWorkReference"

      xml_accessor :sequence_number, :as => Integer, :from => "SequenceNumber", :required => false
      xml_accessor :duration_used, :from => "DurationUsed", :required => false
      xml_accessor :fragment?, :from => "IsFragment", :required => false
      xml_accessor :resource_musical_work_reference, :from => "ResourceMusicalWorkReference", :required => true




end

end end end
