#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20100121/ddexc/catalog_number"
require "ddex/v20100121/ddexc/proprietary_id"

module DDEX module V20100121 module DDEXC  # :nodoc: all

class ResourceId < Element
  include ROXML


  xml_name "ns2:ResourceId"

      xml_accessor :isrc, :from => "ISRC", :required => false
      xml_accessor :ismn, :from => "ISMN", :required => false
      xml_accessor :isan, :from => "ISAN", :required => false
      xml_accessor :visan, :from => "VISAN", :required => false
      xml_accessor :isbn, :from => "ISBN", :required => false
      xml_accessor :issn, :from => "ISSN", :required => false
      xml_accessor :sici, :from => "SICI", :required => false
      xml_accessor :catalog_number, :as => DDEX::V20100121::DDEXC::CatalogNumber, :from => "CatalogNumber", :required => false
      xml_accessor :proprietary_ids, :as => [DDEX::V20100121::DDEXC::ProprietaryId], :from => "ProprietaryId", :required => false




end

end end end
