#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module V20100121 module DDEXC  # :nodoc: all

class RightShareCreationReferenceList < Element
  include ROXML


  xml_name "ns2:RightShareCreationReferenceList"

      xml_accessor :right_share_work_references, :as => [], :from => "RightShareWorkReference", :required => false
      xml_accessor :right_share_resource_references, :as => [], :from => "RightShareResourceReference", :required => false
      xml_accessor :right_share_release_references, :as => [], :from => "RightShareReleaseReference", :required => false




end

end end end
