#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-05-19 14:17:26 +1200
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20100121/ddexc/reason"
require "ddex/v20100121/ddexc/release_id"

module DDEX module V20100121 module DDEXC  # :nodoc: all

class SalesReportingProxyReleaseId < Element
  include ROXML


  xml_name "ns2:SalesReportingProxyReleaseId"

      xml_accessor :release_id, :as => DDEX::V20100121::DDEXC::ReleaseId, :from => "ReleaseId", :required => true
      xml_accessor :reason, :as => DDEX::V20100121::DDEXC::Reason, :from => "Reason", :required => true




end

end end end
