#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-09 22:38:57 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20100712/ddexc/comment"
require "ddex/v20100712/ddexc/simple_profile_messaging_party"

module DDEX module V20100712 module DDEXC  # :nodoc: all

class DDEX::V20100712::DDEXC::SimpleProfileMessageHeader < Element
  include ROXML


  xml_name "SimpleProfileMessageHeader"

      xml_accessor :message_thread_id, :from => "MessageThreadId", :required => true
      xml_accessor :message_id, :from => "MessageId", :required => true
      xml_accessor :message_file_name, :from => "MessageFileName", :required => false
      xml_accessor :message_sender, :as => DDEX::V20100712::DDEXC::SimpleProfileMessagingParty, :from => "MessageSender", :required => true
      xml_accessor :message_recipient, :as => DDEX::V20100712::DDEXC::SimpleProfileMessagingParty, :from => "MessageRecipient", :required => true
      xml_accessor :message_created_date_time, :as => DateTime, :from => "MessageCreatedDateTime", :required => true
      xml_accessor :comment, :as => DDEX::V20100712::DDEXC::Comment, :from => "Comment", :required => false
      xml_accessor :message_control_type, :from => "MessageControlType", :required => false



      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false



end

end end end
