#
# Auto-generated by jaxb2ruby v0.0.1 on 2017-03-09 22:38:57 +0000
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20100712/ddexc/party_id"
require "ddex/v20100712/ddexc/simple_profile_party_name"

module DDEX module V20100712 module DDEXC  # :nodoc: all

class DDEX::V20100712::DDEXC::SimpleProfilePartyDescriptor < Element
  include ROXML


  xml_name "SimpleProfilePartyDescriptor"

      xml_accessor :party_name, :as => DDEX::V20100712::DDEXC::SimpleProfilePartyName, :from => "PartyName", :required => false
      xml_accessor :party_id, :as => DDEX::V20100712::DDEXC::PartyId, :from => "PartyId", :required => false




end

end end end
