#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v383/description"
require "ddex/ern/v383/rating_agency"

module DDEX module ERN module V383  # :nodoc: all

class DDEX::ERN::V383::AvRating < Element
  include ROXML


  xml_name "AvRating"

      xml_accessor :rating_text, :from => "RatingText", :required => true
      xml_accessor :rating_agency, :as => DDEX::ERN::V383::RatingAgency, :from => "RatingAgency", :required => true
      xml_accessor :rating_scheme_descriptions, :as => [DDEX::ERN::V383::Description], :from => "RatingSchemeDescription", :required => false


  

end

end end end
