#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v383/description"
require "ddex/ern/v383/price"
require "ddex/ern/v383/price_range_type"
require "ddex/ern/v383/price_type"

module DDEX module ERN module V383  # :nodoc: all

class DDEX::ERN::V383::PriceInformation < Element
  include ROXML


  xml_name "PriceInformation"

      xml_accessor :description, :as => DDEX::ERN::V383::Description, :from => "Description", :required => false
      xml_accessor :price_range_type, :as => DDEX::ERN::V383::PriceRangeType, :from => "PriceRangeType", :required => false
      xml_accessor :price_type, :as => DDEX::ERN::V383::PriceType, :from => "PriceType", :required => false
      xml_accessor :wholesale_price_per_unit, :as => DDEX::ERN::V383::Price, :from => "WholesalePricePerUnit", :required => false
      xml_accessor :bulk_order_wholesale_price_per_unit, :as => DDEX::ERN::V383::Price, :from => "BulkOrderWholesalePricePerUnit", :required => false
      xml_accessor :suggested_retail_price, :as => DDEX::ERN::V383::Price, :from => "SuggestedRetailPrice", :required => false


  
      xml_accessor :type, :from => "@PriceType", :required => false
    
  

end

end end end
