#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v383/current_territory_code"
require "ddex/ern/v383/label_name"
require "ddex/ern/v383/name"
require "ddex/ern/v383/rights_agreement_id"

module DDEX module ERN module V383  # :nodoc: all

class DDEX::ERN::V383::ReleaseSummaryDetailsByTerritory < Element
  include ROXML


  xml_name "ReleaseSummaryDetailsByTerritory"

      xml_accessor :excluded_territory_codes, :as => [DDEX::ERN::V383::CurrentTerritoryCode], :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :as => [DDEX::ERN::V383::CurrentTerritoryCode], :from => "TerritoryCode", :required => false
      xml_accessor :display_artist_names, :as => [DDEX::ERN::V383::Name], :from => "DisplayArtistName", :required => false
      xml_accessor :label_names, :as => [DDEX::ERN::V383::LabelName], :from => "LabelName", :required => false
      xml_accessor :rights_agreement_id, :as => DDEX::ERN::V383::RightsAgreementId, :from => "RightsAgreementId", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
