#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V383  # :nodoc: all

class DDEX::ERN::V383::ResourceGroupResourceReferenceList < Element
  include ROXML


  xml_name "ResourceGroupResourceReferenceList"

      xml_accessor :resource_group_resource_references, :as => [], :from => "ResourceGroupResourceReference", :required => true


  

end

end end end
