#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v383/reason"
require "ddex/ern/v383/reason_type"
require "ddex/ern/v383/release_id"

module DDEX module ERN module V383  # :nodoc: all

class DDEX::ERN::V383::SalesReportingProxyReleaseId < Element
  include ROXML


  xml_name "SalesReportingProxyReleaseId"

      xml_accessor :release_id, :as => DDEX::ERN::V383::ReleaseId, :from => "ReleaseId", :required => true
      xml_accessor :reason, :as => DDEX::ERN::V383::Reason, :from => "Reason", :required => false
      xml_accessor :reason_type, :as => DDEX::ERN::V383::ReasonType, :from => "ReasonType", :required => true


  

end

end end end
