#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v383/title_text"
require "ddex/ern/v383/typed_sub_title"

module DDEX module ERN module V383  # :nodoc: all

class DDEX::ERN::V383::Title < Element
  include ROXML


  xml_name "Title"

      xml_accessor :title_text, :as => DDEX::ERN::V383::TitleText, :from => "TitleText", :required => true
      xml_accessor :sub_titles, :as => [DDEX::ERN::V383::TypedSubTitle], :from => "SubTitle", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  
      xml_accessor :title_type, :from => "@TitleType", :required => false
    
  

end

end end end
