#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v383/c_line"
require "ddex/ern/v383/current_territory_code"
require "ddex/ern/v383/detailed_resource_contributor"
require "ddex/ern/v383/event_date"
require "ddex/ern/v383/fulfillment_date"
require "ddex/ern/v383/genre"
require "ddex/ern/v383/indirect_resource_contributor"
require "ddex/ern/v383/keywords"
require "ddex/ern/v383/name"
require "ddex/ern/v383/p_line"
require "ddex/ern/v383/parental_warning_type"
require "ddex/ern/v383/synopsis"
require "ddex/ern/v383/technical_user_defined_resource_details"
require "ddex/ern/v383/title"
require "ddex/ern/v383/user_defined_value"

module DDEX module ERN module V383  # :nodoc: all

class DDEX::ERN::V383::UserDefinedResourceDetailsByTerritory < Element
  include ROXML


  xml_name "UserDefinedResourceDetailsByTerritory"

      xml_accessor :excluded_territory_codes, :as => [DDEX::ERN::V383::CurrentTerritoryCode], :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :as => [DDEX::ERN::V383::CurrentTerritoryCode], :from => "TerritoryCode", :required => false
      xml_accessor :titles, :as => [DDEX::ERN::V383::Title], :from => "Title", :required => false
      xml_accessor :resource_contributors, :as => [DDEX::ERN::V383::DetailedResourceContributor], :from => "ResourceContributor", :required => false
      xml_accessor :indirect_resource_contributors, :as => [DDEX::ERN::V383::IndirectResourceContributor], :from => "IndirectResourceContributor", :required => false
      xml_accessor :display_artist_names, :as => [DDEX::ERN::V383::Name], :from => "DisplayArtistName", :required => false
      xml_accessor :user_defined_values, :as => [DDEX::ERN::V383::UserDefinedValue], :from => "UserDefinedValue", :required => false
      xml_accessor :p_lines, :as => [DDEX::ERN::V383::PLine], :from => "PLine", :required => false
      xml_accessor :c_lines, :as => [DDEX::ERN::V383::CLine], :from => "CLine", :required => false
      xml_accessor :resource_release_date, :as => DDEX::ERN::V383::EventDate, :from => "ResourceReleaseDate", :required => false
      xml_accessor :original_resource_release_date, :as => DDEX::ERN::V383::EventDate, :from => "OriginalResourceReleaseDate", :required => false
      xml_accessor :fulfillment_date, :as => DDEX::ERN::V383::FulfillmentDate, :from => "FulfillmentDate", :required => false
      xml_accessor :keywords, :as => [DDEX::ERN::V383::Keywords], :from => "Keywords", :required => false
      xml_accessor :synopsis, :as => DDEX::ERN::V383::Synopsis, :from => "Synopsis", :required => false
      xml_accessor :genres, :as => [DDEX::ERN::V383::Genre], :from => "Genre", :required => false
      xml_accessor :parental_warning_types, :as => [DDEX::ERN::V383::ParentalWarningType], :from => "ParentalWarningType", :required => false
      xml_accessor :technical_user_defined_resource_details, :as => [DDEX::ERN::V383::TechnicalUserDefinedResourceDetails], :from => "TechnicalUserDefinedResourceDetails", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
