#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20110120/ddexc/collection_type"

module DDEX module V20110120 module DDEXC  # :nodoc: all

class DDEX::V20110120::DDEXC::AmountPerCollection < Element
  include ROXML


  xml_name "AmountPerCollection"

      xml_accessor :amount, :as => Float, :from => "Amount", :required => true
      xml_accessor :collection_type, :as => DDEX::V20110120::DDEXC::CollectionType, :from => "CollectionType", :required => true


  

end

end end end
