#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:26 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module V20110120 module DDEXC  # :nodoc: all

class DDEX::V20110120::DDEXC::CollectionResourceReferenceList < Element
  include ROXML


  xml_name "CollectionResourceReferenceList"

      xml_accessor :collection_resource_references, :as => [], :from => "CollectionResourceReference", :required => true


  

end

end end end
