#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20110120/ddexc/message_audit_trail_event"

module DDEX module V20110120 module DDEXC  # :nodoc: all

class DDEX::V20110120::DDEXC::MessageAuditTrail < Element
  include ROXML


  xml_name "MessageAuditTrail"

      xml_accessor :message_audit_trail_events, :as => [DDEX::V20110120::DDEXC::MessageAuditTrailEvent], :from => "MessageAuditTrailEvent", :required => true


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
