#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20110120/ddexc/musical_work_contributor_role"
require "ddex/v20110120/ddexc/party_descriptor"
require "ddex/v20110120/ddexc/society_affiliation"

module DDEX module V20110120 module DDEXC  # :nodoc: all

class DDEX::V20110120::DDEXC::MusicalWorkContributor < DDEX::V20110120::DDEXC::PartyDescriptor
  include ROXML


  xml_name "MusicalWorkContributor"

      xml_accessor :musical_work_contributor_roles, :as => [DDEX::V20110120::DDEXC::MusicalWorkContributorRole], :from => "MusicalWorkContributorRole", :required => false
      xml_accessor :society_affiliations, :as => [DDEX::V20110120::DDEXC::SocietyAffiliation], :from => "SocietyAffiliation", :required => false


  

      xml_accessor :sequence_number, :as => Integer, :from => "@SequenceNumber", :required => false
    
  

end

end end end
