#
# Auto-generated by jaxb2ruby v0.0.1 on 2016-07-11 13:50:27 +0100
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/v20110120/ddexc/c_line"
require "ddex/v20110120/ddexc/sound_recording_details_by_territory"

module DDEX module V20110120 module DDEXC  # :nodoc: all

class DDEX::V20110120::DDEXC::VideoDetailsByTerritory < DDEX::V20110120::DDEXC::SoundRecordingDetailsByTerritory
  include ROXML


  xml_name "VideoDetailsByTerritory"

      xml_accessor :c_lines, :as => [DDEX::V20110120::DDEXC::CLine], :from => "CLine", :required => false


  

end

end end end
